# Copyright Amazon.com, Inc. or its affiliates.

version: 0.2

env:
  variables:
    workflow_engine: NEXTFLOW
  shell: bash
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - export BASEDIR="${CODEBUILD_SRC_DIR}"
      - export PATH=$PATH:$BASEDIR
      - export SCRIPTDIR="${BASEDIR}/scripts"
      - mkdir -p $SCRIPTDIR
      - export CICD_SCRIPTS_S3DIR="s3://${DEPLOYBUCKET}/cicd_scripts/"
      - aws s3 cp $CICD_SCRIPTS_S3DIR "${SCRIPTDIR}/" --recursive
      - chmod +x $SCRIPTDIR/*.sh
      - export WFDIR="${CODEBUILD_SRC_DIR}"
  pre_build:
    commands:
      - export ARTIFACTURI="s3://${artifactBucket}/${artifactKey}"
      - export ARTIFACTFOLDER=$(dirname $ARTIFACTURI)
      - export WFNAME=$workflowName
      - export CURRBRANCH=$projectBranch
      - export MAJORV=$(echo ${workflowVersion} | sed s/v//g | cut -d. -f1)
      - export MINORV=$(echo ${workflowVersion} | sed s/v//g | cut -d. -f2)
      - export PATCHV=$(echo ${workflowVersion} | sed s/v//g | cut -d. -f3)
      - export BUILDV=$(echo ${workflowVersion} | sed s/v//g | cut -d. -f4)
      - export TAGNAME="${CURRBRANCH}-${MAJORV}.${MINORV}.${PATCHV}.${BUILDV}"
      - export ARTIFACTNAME="${WFNAME}-${TAGNAME}"
      - export ARTIFACTFILE="workflow"      
      - git config --global user.email "CodeBuild@example.com"
      - git config --global user.name "CodeBuild"
  build:
    commands:
      - mkdir -p $BASEDIR/workflow
      - echo "Artifact URI:${ARTIFACTURI}"
      - aws s3 cp $ARTIFACTURI $BASEDIR/workflow
      - aws s3 cp $ARTIFACTFOLDER/parameter-template.json $BASEDIR/workflow
      - aws s3 cp $ARTIFACTFOLDER/container_pull_manifest.json $BASEDIR/workflow      
      - cd $BASEDIR/workflow
      - echo "Creating Workflow..."
      - echo "You might want to delete previous versions of this workflow"
      - TMPWFINFO=$(aws omics create-workflow --definition-zip fileb://${BASEDIR}/workflow/${ARTIFACTFILE}.zip --parameter-template file://${BASEDIR}/workflow/parameter-template.json --name ${ARTIFACTNAME} --engine $workflow_engine --tags COMMIT_ID=$CODEBUILD_RESOLVED_SOURCE_VERSION,BUILD_SOURCE=$CODEBUILD_BUILD_ID,STARTED_BY=$CODEBUILD_INITIATOR,BRANCH=$CURRBRANCH,MAJOR_VERSION=$MAJORV,MINOR_VERSION=$MINORV,PATCH_VERSION=$PATCHV,BUILD_VERSION=$BUILDV)
      - echo "${TMPWFINFO}" > $BASEDIR/${ARTIFACTFILE}.json
  post_build:
    commands:
      - aws omics list-workflows --type PRIVATE --name ${ARTIFACTNAME}

artifacts:
  files:
    - ${ARTIFACTFILE}.zip
    - ${ARTIFACTFILE}.json
  name: ${ARTIFACTNAME}-$(date +%Y-%m-%d)-$CODEBUILD_RESOLVED_SOURCE_VERSION