version: 0.2

env:
  variables:
    workflow_name: RNAseqQC
    workflow_version: 1.0.0
    artifact_bucket: rnaseq-artifacts
    workflow_engine: NEXTFLOW
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "OS Environment Setup"
      - yum install awscli -y
      - pip3 install boto3
  pre_build:
    commands:
      - env
      - cd src/workflow/nextflow-rnaseq
      - ls
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - zip -R workflow.zip *
      - aws omics create-workflow --definition-zip fileb://workflow.zip --parameter-template file://workflow-parameters.json --name ${workflow_name}-${workflow_version} --engine $workflow_engine --tags COMMIT_ID=$CODEBUILD_RESOLVED_SOURCE_VERSION,BUILD_SOURCE=$CODEBUILD_BUILD_ID,STARTED_BY=$CODEBUILD_INITIATOR
  post_build:
    commands:
      - aws omics list-workflows --type PRIVATE --name ${workflow_name}-${workflow_version}

artifacts:
  files:
    - workflow.zip
  name: ${workflow_name}-v${workflow-version}-$(date +%Y-%m-%d)-$CODEBUILD_RESOLVED_SOURCE_VERSION