Parameters:
  CodeBuildRoleArn:
    Type: String
Resources:
  ECRRepo:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: healthomics-repository
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !Sub "${CodeBuildRoleArn}"
            Action: 
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:PutImage'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:UploadLayerPart'
              - 'ecr:CompleteLayerUpload'
Outputs:
  ECRRepoArn:
    Value: !GetAtt 
      - ECRRepo
      - Arn