Parameters:
  CodeBuildRoleArn:
    Type: String
  CodeCommitProject:
    Type: String
  CodeCommitBranch:
    Type: String
  S3BucketName:
    Type: String
Resources:
  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: healthomics-basicworkflow
      Description: aws HealthOmics Basic Workflow
      ServiceRole: !Ref CodeBuildRoleArn
      Artifacts:
        Type: S3
        Location: !Ref S3BucketName
        Path: artifacts/HealthOmics/
        NamespaceType: BUILD_ID
        Name: output
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        EnvironmentVariables:
        - Name: artifact_bucket
          Type: PLAINTEXT
          Value: !Ref S3BucketName
      Source:
        Location: !Ref CodeCommitProject 
        Type: CODECOMMIT
        BuildSpec: src/workflow/nextflow-rnaseq/buildspec.yml
      SourceVersion:
        !Sub refs/heads/${CodeCommitBranch}
      TimeoutInMinutes: 10