---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: |-
  Lex V2 Appointment Confirmation Bot

Parameters:
  TemplatesS3Bucket:
    Description: >-
      S3 Bucket where those cloudformation templates are stored
    Type: String
  CodeCommitProject:
    Description: >-
     The CodeCommit repo name to use for codebuild builds
    Type: String
  CodeCommitBranch:
    Description: >-
     The CodeCommit branch to use for codebuild builds
    Type: String

Resources:     
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesS3Bucket}.s3.amazonaws.com/healthomics-cicd-iam.yaml
      TimeoutInMinutes: 10
      Parameters:
        CodeCommitProject: 
          !Ref CodeCommitProject   
  ECRStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IamStack
    Properties:
      TemplateURL: !Sub https://${TemplatesS3Bucket}.s3.amazonaws.com/healthomics-cicd-ecr.yaml
      TimeoutInMinutes: 10
      Parameters:
        CodeBuildRoleArn: 
          Fn::GetAtt: [IamStack, Outputs.CodeBuildRoleArn]
  BuildStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ECRStack
    Properties:
      TemplateURL: !Sub https://${TemplatesS3Bucket}.s3.amazonaws.com/healthomics-cicd-buildpipeline.yaml
      TimeoutInMinutes: 10
      Parameters:
        CodeBuildRoleArn:
          Fn::GetAtt: [IamStack, Outputs.CodeBuildRoleArn]
        CodeCommitProject: 
          !Ref CodeCommitProject
        CodeCommitBranch: 
          !Ref CodeCommitBranch
        S3BucketName:
          Fn::GetAtt: [IamStack, Outputs.S3BucketName]


Outputs:
  ECRRepoArn:
   Description: ECR ARN
   Value:
     Fn::GetAtt: [ECRStack, Outputs.ECRRepoArn]