version: 0.2

env:
  variables:
    workflow_major_version: 1
    workflow_minor_version: 0
    workflow_engine: NEXTFLOW
  shell: bash
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - export BASEDIR="${PWD}"
      - export WFDIR="${BASEDIR}/workflow"    
      - chmod +x $BASEDIR/cicd/scripts/*.sh
      - $BASEDIR/cicd/scripts/buildenv_setup.sh
      - export WFID=$(jq -r .id $CODEBUILD_SRC_DIR_Artifact_Build_workflow_build_action/workflow.json)
      - export WFARN=$(jq -r .arn $CODEBUILD_SRC_DIR_Artifact_Build_workflow_build_action/workflow.json)
      - export LASTPATCHVER=$($BASEDIR/cicd/scripts/get_last_patch.sh)
      - export TAGNAME=$($BASEDIR/cicd/scripts/get_next_tag_name.sh ${LASTPATCHVER})
      - export NEXTPATCHVER="${TAGNAME##*.}"
      - export WFTESTPARAMSFILE=$WFDIR/workflow-parameters.json
  pre_build:
    commands:
      - git config --global user.email "CodeBuild@example.com"
      - git config --global user.name "CodeBuild"
  build:
    commands:
      - echo "Launch workflow deployed in previous step"
      - bash -x $BASEDIR/cicd/scripts/test_workflow.sh