version: 0.2

env:
  variables:
    workflow_name: RNAseqQC
    workflow_major_version: 1
    workflow_minor_version: 0
    workflow_engine: NEXTFLOW
  shell: bash
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - export AWS_ACCOUNTID=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')
      - export BASEDIR="${PWD}"
      - export WFDIR="${BASEDIR}/workflow/nextflow-rnaseq"    
      - chmod +x $BASEDIR/cicd/scripts/*.sh
      - $BASEDIR/cicd/scripts/buildenv_setup.sh
      - export WFID=$(jq -r .id $CODEBUILD_SRC_DIR_Artifact_Build_workflows_build_action/workflow.json)
      - export WFARN=$(jq -r .arn $CODEBUILD_SRC_DIR_Artifact_Build_workflows_build_action/workflow.json)       
  pre_build:
    commands:
      - git config --global user.email "CodeBuild@example.com"
      - git config --global user.name "CodeBuild"
  build:
    commands:
      - echo "TODO --> Launch workflow deployed in previous step"
      - echo " Decide wether to do it locally, or using healthomics (way longer run time)"
      - echo "Tests failed, delete temporary workflow with ARN ${WFARN}"
      - aws omics delete-workflow --id $WFID
